<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WebhookServer.Core\WebhookServer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\resources\webhook-server.ico</ApplicationIcon>
    <AssemblyTitle>Webhook Server</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\..\resources\webhook-server.ico" Link="webhook-server.ico" />
    <Resource Include="..\..\resources\webhook-server.png" Link="webhook-server.png" />
  </ItemGroup>

</Project>
